run:
  deadline: 5m
  skip-files: []
linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 12.0
  maligned:
    suggest-new: true
  goconst:
    min-len: 3.0
    min-occurrences: 3.0
  misspell:
    locale: "UK"
    ignore-words:
     - listend
     - analyses
     - cancelling
     - color
     - colors
linters:
  enable:
    - vet
    - golint
    - gofmt
    - deadcode
    - varcheck
    - structcheck
    - misspell
    - errcheck
    - gosimple
    - govet
    - ineffassign
issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude: []