trigger:
  branches:
    include:
    - master
    - pipeline-with-tests
  paths:
    exclude:
    - README.md

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GoTool@0
  displayName: 'Using Go v1.12'
  inputs:
    version: '1.12'

- task: Go@0
  displayName: 'Resolving Dependencies'
  inputs:
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: Go@0
  displayName: 'Building Abstrakt'
  inputs:
    command: build
    arguments: '-o "$(Build.Repository.Name)"'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- script: |
    make lint-all
  displayName: 'Lint Abstrakt'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: Go@0
  displayName: 'Test Abstrakt'
  inputs:
    command: test
    arguments: -v ./... -cover -coverprofile=coverage.txt -race -covermode=atomic 2>&1 | go-junit-report > report.xml
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: $(System.DefaultWorkingDirectory)/**/report.xml

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura 
    summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.xml
    reportDirectory: $(System.DefaultWorkingDirectory)/**/coverage

- task: ArchiveFiles@2
  displayName: 'Archive Files'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    rootFolderOrFile: '$(Build.Repository.LocalPath)/$(Build.Repository.Name)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    artifactName: drop
